# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

from snakemake.utils import min_version
min_version("6.0")

import yaml
import pandas as pd
import ast
configfile: "config/config.yaml"
samples = pd.read_table(config["samples_tsv"], converters={"files": ast.literal_eval}).set_index("sample_name", drop=False)
wildcard_constraints:
    sample ="|".join(samples.index.tolist())

report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

#module dna_seq:
#	snakefile: "https://raw.githubusercontent.com/jensenrichardson/dna-preprocess/main/Snakefile"
#	config: "config/dna_config.yaml"
#use rule * from dna_seq

dna_preprocess_config = {}
with open(config["dna_preprocess_config"]) as dna_preprocess_config_file:
    dna_preprocess_config = yaml.load(dna_preprocess_config_file, Loader=yaml.FullLoader)
module DnaPreprocess:
    snakefile: "https://raw.githubusercontent.com/jensenrichardson/dna-preprocess/main/Snakefile"
    config: dna_preprocess_config
use rule * from DnaPreprocess as DnaPreprocess*

rule all:
    input: expand("11-FilterMutectCalls/{sample}.filtered.vcf", sample=samples.to_dict('index'))
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
	


include: "rules/mutect2.smk"
include: "rules/LearnReadOrientationModel.smk"
include: "rules/GetPileupSummaries.smk"
include: "rules/CalculateContamination.smk"
include: "rules/FilterMutectCalls.smk"
